# Generated by Django 5.2.17 on 2026-10-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("about", "About SiaNexis"),
                            ("mission", "Mission"),
                            ("approach", "Research approach"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("body", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="about/")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("organization_name", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=80)),
                (
                    "collaboration_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic collaboration"),
                            ("hospital", "Hospital collaboration"),
                            ("research_center", "Research center collaboration"),
                            ("international", "International collaboration"),
                            ("multicenter", "Multicenter collaboration"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Project description"),
                ),
                ("logo", models.ImageField(blank=True, upload_to="collaborations/")),
                ("link", models.URLField(blank=True, verbose_name="Website / link")),
            ],
            options={
                "ordering": ["collaboration_type", "order", "organization_name"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("research_project", "Research project"),
                            ("data_analysis", "Statistical / Data analysis"),
                            ("collaboration", "Research collaboration"),
                            ("multicenter", "Multicenter study"),
                            ("partnership", "Institutional partnership"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("email_sent", models.BooleanField(default=False, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("research", "Research opportunity"),
                            ("open_project", "Open project"),
                            ("collaborators", "Call for collaborators"),
                            ("sites", "Call for research sites"),
                            ("volunteer", "Volunteer / expert opportunity"),
                            ("student", "Student / researcher opportunity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "apply_link",
                    models.URLField(
                        blank=True, help_text="Leave blank to use the contact form."
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "opportunities",
                "ordering": ["kind", "order", "deadline"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("logo", models.ImageField(blank=True, upload_to="orgs/")),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=170)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=140)),
                ("summary", models.CharField(blank=True, max_length=240)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text. Blank lines become paragraphs.",
                    ),
                ),
                ("show_in_menu", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResearchArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=170)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("summary", models.CharField(blank=True, max_length=240)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="An emoji or short symbol.", max_length=8
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="areas/")),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name_plural": "service categories",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="SiaNexis", max_length=80)),
                (
                    "tagline",
                    models.CharField(
                        default="Research, data and computation for better science",
                        max_length=160,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="branding/")),
                (
                    "hero_title",
                    models.CharField(
                        default="Advancing research through design, data and collaboration",
                        max_length=160,
                    ),
                ),
                ("hero_text", models.TextField(blank=True)),
                (
                    "intro_text",
                    models.TextField(
                        blank=True,
                        help_text="Short 'about SiaNexis' text on the home page.",
                    ),
                ),
                (
                    "cta_title",
                    models.CharField(
                        default="Start a project or propose a collaboration",
                        max_length=120,
                    ),
                ),
                ("cta_text", models.CharField(blank=True, max_length=240)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("footer_text", models.CharField(blank=True, max_length=200)),
                (
                    "default_meta_description",
                    models.CharField(blank=True, max_length=170),
                ),
                (
                    "analytics_snippet",
                    models.TextField(
                        blank=True,
                        help_text="Optional tracking script (e.g. analytics).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[("team", "Team"), ("advisory", "Advisory Board")],
                        default="team",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=160)),
                ("affiliation", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("profile_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["group", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("program", "Research training program"),
                            ("workshop", "Workshop"),
                            ("course", "Research course"),
                            ("institutional", "Institutional training"),
                            ("mentorship", "Research mentorship"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=80)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        help_text="Online / In person / Hybrid",
                        max_length=80,
                    ),
                ),
                ("registration_link", models.URLField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="training/")),
            ],
            options={
                "ordering": ["kind", "order", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=170)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "problem",
                    models.TextField(
                        blank=True, verbose_name="Research question / problem"
                    ),
                ),
                ("role", models.TextField(blank=True, verbose_name="SiaNexis role")),
                ("methodology", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True, verbose_name="Outcome")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="projects/")),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Show on the home page."
                    ),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="core.organization",
                        verbose_name="Collaborating institutions",
                    ),
                ),
                (
                    "research_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="core.researcharea",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("paper", "Published paper"),
                            ("manuscript", "Ongoing manuscript"),
                            ("output", "Research output"),
                        ],
                        default="paper",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("journal", models.CharField(blank=True, max_length=200)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 10.1000/xyz123 (no URL prefix)",
                        max_length=120,
                    ),
                ),
                ("external_link", models.URLField(blank=True)),
                ("pdf", models.FileField(blank=True, upload_to="publications/")),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HubItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=170)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("program", "Research Programs"),
                            ("ongoing", "Ongoing Studies"),
                            ("multicenter", "Multicenter Studies"),
                            ("network", "Research Networks"),
                            ("collaboration", "Research Collaborations"),
                            ("opportunity", "Research Opportunities"),
                            ("project", "Research Projects"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("recruiting", "Recruiting"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="hub/")),
                ("link", models.URLField(blank=True)),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
                (
                    "research_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.researcharea",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "order", "title"],
            },
        ),
    ]
