# Generated by Django 5.2.17 on 2026-10-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutsection",
            name="body_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="title_ar",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="title_en",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="country_ar",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="country_en",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="description_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Project description"
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Project description"
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="organization_name_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="organization_name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="summary_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="summary_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="country_ar",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="country_en",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="body_ar",
            field=models.TextField(
                blank=True,
                help_text="Plain text. Blank lines become paragraphs.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="body_en",
            field=models.TextField(
                blank=True,
                help_text="Plain text. Blank lines become paragraphs.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="summary_en",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_ar",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="methodology_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="methodology_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="outcome_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Outcome"),
        ),
        migrations.AddField(
            model_name="project",
            name="outcome_en",
            field=models.TextField(blank=True, null=True, verbose_name="Outcome"),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Research question / problem"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Research question / problem"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="role_ar",
            field=models.TextField(blank=True, null=True, verbose_name="SiaNexis role"),
        ),
        migrations.AddField(
            model_name="project",
            name="role_en",
            field=models.TextField(blank=True, null=True, verbose_name="SiaNexis role"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="title_ar",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="title_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="meta_description_ar",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="meta_description_en",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="meta_title_ar",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="meta_title_en",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to use the title.",
                max_length=70,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="summary_en",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="title_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="title_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="title_ar",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="title_en",
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_ar",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="description_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="title_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="title_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_text_ar",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_text_en",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_title_ar",
            field=models.CharField(
                default="Start a project or propose a collaboration",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cta_title_en",
            field=models.CharField(
                default="Start a project or propose a collaboration",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_meta_description_ar",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="default_meta_description_en",
            field=models.CharField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_text_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_ar",
            field=models.CharField(
                default="Advancing research through design, data and collaboration",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hero_title_en",
            field=models.CharField(
                default="Advancing research through design, data and collaboration",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="intro_text_ar",
            field=models.TextField(
                blank=True,
                help_text="Short 'about SiaNexis' text on the home page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="intro_text_en",
            field=models.TextField(
                blank=True,
                help_text="Short 'about SiaNexis' text on the home page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_name_ar",
            field=models.CharField(default="SiaNexis", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_name_en",
            field=models.CharField(default="SiaNexis", max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline_ar",
            field=models.CharField(
                default="Research, data and computation for better science",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tagline_en",
            field=models.CharField(
                default="Research, data and computation for better science",
                max_length=160,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="affiliation_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="affiliation_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_ar",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_en",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_ar",
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="role_en",
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="duration_ar",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="duration_en",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="format_ar",
            field=models.CharField(
                blank=True,
                help_text="Online / In person / Hybrid",
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="format_en",
            field=models.CharField(
                blank=True,
                help_text="Online / In person / Hybrid",
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="summary_ar",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="summary_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="title_ar",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="organization",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Organization"
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("research_project", "Research project"),
                    ("data_analysis", "Statistical / Data analysis"),
                    ("collaboration", "Research collaboration"),
                    ("multicenter", "Multicenter study"),
                    ("partnership", "Institutional partnership"),
                    ("training", "Training"),
                    ("other", "Other"),
                ],
                max_length=30,
                verbose_name="Request type",
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="subject",
            field=models.CharField(blank=True, max_length=200, verbose_name="Subject"),
        ),
    ]
