# Generated by Django 5.2.17 on 2026-10-02 19:21

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aboutsection_body_ar_aboutsection_body_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("language", models.CharField(blank=True, max_length=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "token",
                    models.CharField(
                        default=secrets.token_urlsafe,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_title_en",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                        null=True,
                    ),
                ),
                (
                    "meta_title_ar",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the title.",
                        max_length=70,
                        null=True,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=170)),
                (
                    "meta_description_en",
                    models.CharField(blank=True, max_length=170, null=True),
                ),
                (
                    "meta_description_ar",
                    models.CharField(blank=True, max_length=170, null=True),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Auto-filled from the title.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_ar", models.CharField(max_length=200, null=True)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("summary_en", models.CharField(blank=True, max_length=300, null=True)),
                ("summary_ar", models.CharField(blank=True, max_length=300, null=True)),
                ("body", models.TextField()),
                ("body_en", models.TextField(null=True)),
                ("body_ar", models.TextField(null=True)),
                ("image", models.ImageField(blank=True, upload_to="news/")),
                ("author_name", models.CharField(blank=True, max_length=120)),
                (
                    "published_at",
                    models.DateField(
                        help_text="Shown on the post and used for ordering."
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created"],
            },
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="confirmation_sent",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="language",
            field=models.CharField(blank=True, editable=False, max_length=5),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum seats. Leave blank for unlimited; extra sign-ups go on a waiting list.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="registration_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="registration_link",
            field=models.URLField(
                blank=True,
                help_text="External link. Leave blank to use the built-in registration form.",
            ),
        ),
        migrations.CreateModel(
            name="TrainingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organization"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Phone"),
                ),
                (
                    "message",
                    models.TextField(blank=True, verbose_name="Notes (optional)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("waitlist", "Waiting list"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(blank=True, editable=False, max_length=5),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="core.trainingprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "email"), name="one_registration_per_email"
                    )
                ],
            },
        ),
    ]
