# Generated by Django 5.2.17 on 2026-10-02 19:37

import core.fields
from django.db import migrations, models


def fill_team_slugs(apps, schema_editor):
    from django.utils.text import slugify

    TeamMember = apps.get_model("core", "TeamMember")
    used = set()
    for member in TeamMember.objects.filter(slug__isnull=True):
        base = slugify(member.name_en or member.name) or "member"
        slug, n = base, 2
        while slug in used or TeamMember.objects.filter(slug=slug).exists():
            slug, n = f"{base}-{n}", n + 1
        used.add(slug)
        member.slug = slug
        member.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Untick to hide from the public site."
                    ),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: show on the site from this date/time.",
                        null=True,
                    ),
                ),
                (
                    "unpublish_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: hide from the site after this date/time.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=80)),
                ("label_en", models.CharField(max_length=80, null=True)),
                ("label_ar", models.CharField(max_length=80, null=True)),
                ("value", models.PositiveIntegerField()),
                (
                    "suffix",
                    models.CharField(blank=True, help_text="e.g. + or %", max_length=8),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Position on the map. Use the 'Fill coordinates from country' action, or enter manually.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contactrequest",
            name="crm_status",
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hubitem",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="crm_status",
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_partner",
            field=models.BooleanField(
                default=False,
                help_text="Show this logo in the partners strip on the home page.",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="researcharea",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="ga_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="Google Analytics 4 ID, e.g. G-XXXXXXXXXX. Loaded only after the visitor accepts cookies.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="plausible_domain",
            field=models.CharField(
                blank=True,
                help_text="Plausible domain, e.g. sianexis.com (cookie-free analytics).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_url",
            field=models.CharField(
                blank=True,
                help_text="Link of the privacy policy page, e.g. /en/p/privacy/",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="google_scholar_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="orcid",
            field=models.CharField(
                blank=True, help_text="e.g. 0000-0002-1825-0097", max_length=19
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="publications",
            field=models.ManyToManyField(
                blank=True, related_name="team_members", to="core.publication"
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-filled from the title.",
                max_length=140,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: show on the site from this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="unpublish_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional: hide from the site after this date/time.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trainingregistration",
            name="crm_status",
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
        migrations.AlterField(
            model_name="aboutsection",
            name="image",
            field=core.fields.OptimizedImageField(blank=True, upload_to="about/"),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="logo",
            field=core.fields.OptimizedImageField(
                blank=True, upload_to="collaborations/"
            ),
        ),
        migrations.AlterField(
            model_name="hubitem",
            name="image",
            field=core.fields.OptimizedImageField(blank=True, upload_to="hub/"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=core.fields.OptimizedImageField(blank=True, upload_to="orgs/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=core.fields.OptimizedImageField(blank=True, upload_to="news/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=core.fields.OptimizedImageField(blank=True, upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="researcharea",
            name="image",
            field=core.fields.OptimizedImageField(blank=True, upload_to="areas/"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="logo",
            field=core.fields.OptimizedImageField(blank=True, upload_to="branding/"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=core.fields.OptimizedImageField(blank=True, upload_to="team/"),
        ),
        migrations.AlterField(
            model_name="trainingprogram",
            name="image",
            field=core.fields.OptimizedImageField(blank=True, upload_to="training/"),
        ),
        migrations.RunPython(fill_team_slugs, migrations.RunPython.noop),
]
