# Generated by Django 5.2.17 on 2026-10-02 19:57

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_trust_and_ops"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="abstract",
            field=models.TextField(
                blank=True, help_text="Use this for an unstructured abstract."
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="abstract_background",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="abstract_conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="abstract_methods",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="abstract_results",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="accepted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="accesses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="altmetric",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="article_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="publication",
            name="citations",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("research", "Research"),
                    ("review", "Review"),
                    ("case_study", "Case study"),
                    ("short_report", "Short report"),
                    ("other", "Article"),
                ],
                default="research",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="issn",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="publication",
            name="issue",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="publication",
            name="keywords",
            field=models.CharField(
                blank=True, help_text="Comma separated.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="license",
            field=models.CharField(
                blank=True, help_text="e.g. CC BY 4.0", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="license_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="mentions",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="open_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="published_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="publisher",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="publication",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="rights_text",
            field=models.TextField(
                blank=True, help_text="Rights and permissions statement."
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-filled from the title.",
                max_length=140,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="subjects",
            field=models.CharField(
                blank=True,
                help_text="Comma separated. Shown as related subjects.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="volume",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text",
            field=models.CharField(
                blank=True,
                help_text="Optional notice bar shown at the top of article pages.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="ArticleAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name as displayed.", max_length=140
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional, for correct citations.",
                        max_length=80,
                    ),
                ),
                (
                    "family_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional, for correct citations.",
                        max_length=80,
                    ),
                ),
                ("affiliation", models.CharField(blank=True, max_length=300)),
                ("corresponding", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("orcid", models.CharField(blank=True, max_length=19)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_list",
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("figure", "Figure"), ("table", "Table")],
                        default="figure",
                        max_length=10,
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="e.g. Fig. 1 or Table 1", max_length=20
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    core.fields.OptimizedImageField(blank=True, upload_to="articles/"),
                ),
                (
                    "table_html",
                    models.TextField(blank=True, help_text="HTML <table> for tables."),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Footnote under the figure/table.",
                        max_length=500,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="figures",
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "number"],
            },
        ),
        migrations.CreateModel(
            name="ArticleLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("similar", "Similar content"),
                            ("related", "Related subject / link"),
                        ],
                        default="similar",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField()),
                ("source", models.CharField(blank=True, max_length=160)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("background", "Background"),
                            ("methods", "Methods"),
                            ("results", "Results"),
                            ("conclusion", "Conclusion"),
                            ("introduction", "Introduction"),
                            ("methodology", "Methodology"),
                            ("discussion", "Discussion"),
                            ("limitations", "Limitations"),
                            ("conclusions", "Conclusions"),
                            ("data_availability", "Data availability"),
                            ("author_info", "Author information"),
                            ("ethics", "Ethics declarations"),
                            ("other", "Other section"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the standard title.",
                        max_length=160,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Blank line = new paragraph. '### Title' = sub-heading. '- item' = bullet. [12] links to reference 12. [[fig:1]] / [[table:1]] place a figure or table."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ArticleReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("text", models.TextField(help_text="Full reference as printed.")),
                ("authors", models.CharField(blank=True, max_length=500)),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Journal / publisher and year.",
                        max_length=300,
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField(blank=True, max_length=600)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publication", "number"), name="unique_ref_number"
                    )
                ],
            },
        ),
    ]
