# Generated by Django 5.2.17 on 2026-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_article_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_ar",
            field=models.CharField(
                blank=True,
                help_text="Optional notice bar shown at the top of article pages.",
                max_length=240,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="announcement_text_en",
            field=models.CharField(
                blank=True,
                help_text="Optional notice bar shown at the top of article pages.",
                max_length=240,
                null=True,
            ),
        ),
    ]
