# Generated by Django 5.2.17 on 2026-10-02 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_announcement_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Shown on the post and used for ordering.",
            ),
        ),
    ]
