"""English -> Arabic labels for the CMS (field names, help texts, model names, sections).

Single source used by core/models.py (to apply lazy translations) and tools/i18n_build.py (to build locale/ar).
"""

FIELDS = {
    "address": ("Address", "العنوان"), "affiliation": ("Affiliation", "الجهة التابع لها"),
    "analytics_snippet": ("Analytics script", "كود التحليلات"), "apply_link": ("Application link", "رابط التقديم"),
    "assigned_to": ("Assigned to", "مُسنَد إلى"), "author_name": ("Author", "الكاتب"), "authors": ("Authors", "المؤلفون"),
    "bio": ("Biography", "نبذة تعريفية"), "body": ("Content", "المحتوى"), "capacity": ("Capacity (seats)", "السعة (عدد المقاعد)"),
    "category": ("Category", "التصنيف"), "collaboration_type": ("Collaboration type", "نوع التعاون"),
    "confirmation_sent": ("Confirmation email sent", "تم إرسال رسالة التأكيد"), "contact_email": ("Contact email", "بريد التواصل"),
    "country": ("Country", "الدولة"), "created": ("Created", "تاريخ الإنشاء"), "cta_text": ("Call-to-action text", "نص الدعوة لاتخاذ إجراء"),
    "cta_title": ("Call-to-action title", "عنوان الدعوة لاتخاذ إجراء"), "deadline": ("Deadline", "الموعد النهائي"),
    "default_meta_description": ("Default meta description", "وصف الموقع الافتراضي (SEO)"), "description": ("Description", "الوصف"),
    "doi": ("DOI", "معرّف DOI"), "duration": ("Duration", "المدة"), "email": ("Email", "البريد الإلكتروني"),
    "email_sent": ("Notification email sent", "تم إرسال إشعار البريد"), "external_link": ("External link", "رابط خارجي"),
    "featured": ("Featured", "مميّز"), "footer_text": ("Footer text", "نص التذييل"), "format": ("Format", "الصيغة"),
    "group": ("Group", "المجموعة"), "hero_text": ("Hero text", "نص الواجهة الرئيسية"), "hero_title": ("Hero title", "عنوان الواجهة الرئيسية"),
    "icon": ("Icon", "الأيقونة"), "image": ("Image", "الصورة"), "institutions": ("Collaborating institutions", "المؤسسات المتعاونة"),
    "internal_notes": ("Internal notes", "ملاحظات داخلية"), "intro_text": ("Introduction text", "النص التعريفي"),
    "is_active": ("Active", "نشط"), "is_published": ("Published", "منشور"), "journal": ("Journal", "المجلة"),
    "kind": ("Type", "النوع"), "language": ("Language", "اللغة"), "link": ("Website / link", "الموقع / الرابط"),
    "linkedin_url": ("LinkedIn URL", "رابط LinkedIn"), "logo": ("Logo", "الشعار"), "message": ("Message", "الرسالة"),
    "meta_description": ("Meta description", "وصف الصفحة (SEO)"), "meta_title": ("Meta title", "عنوان الصفحة (SEO)"),
    "methodology": ("Methodology", "المنهجية"), "name": ("Name", "الاسم"), "order": ("Display order", "ترتيب العرض"),
    "organization": ("Organization", "الجهة / المؤسسة"), "organization_name": ("Organization name", "اسم الجهة"),
    "outcome": ("Outcome", "النتيجة"), "pdf": ("PDF file", "ملف PDF"), "phone": ("Phone", "الهاتف"), "photo": ("Photo", "الصورة الشخصية"),
    "problem": ("Research question / problem", "السؤال البحثي / المشكلة"), "profile_url": ("Profile link", "رابط الملف الشخصي"),
    "program": ("Program", "البرنامج"), "published_at": ("Publication date", "تاريخ النشر"),
    "registration_link": ("Registration link", "رابط التسجيل"), "registration_open": ("Registration open", "التسجيل مفتوح"),
    "related_project": ("Related project", "مشروع ذو صلة"), "request_type": ("Request type", "نوع الطلب"),
    "research_area": ("Research area", "المجال البحثي"), "role": ("SiaNexis role", "دور SiaNexis"),
    "show_in_menu": ("Show in menu", "إظهار في القائمة"), "site_name": ("Site name", "اسم الموقع"), "slug": ("URL slug", "الرابط المختصر"),
    "start_date": ("Start date", "تاريخ البدء"), "status": ("Status", "الحالة"), "subject": ("Subject", "الموضوع"),
    "summary": ("Summary", "الملخص"), "tagline": ("Tagline", "الشعار النصي"), "title": ("Title", "العنوان"),
    "token": ("Token", "الرمز"), "twitter_url": ("X / Twitter URL", "رابط X / Twitter"), "updated": ("Updated", "تاريخ التحديث"),
    "publish_at": ("Publish from", "نشر اعتبارًا من"), "unpublish_at": ("Hide after", "إخفاء بعد"),
    "latitude": ("Latitude", "خط العرض"), "longitude": ("Longitude", "خط الطول"), "orcid": ("ORCID iD", "معرّف ORCID"),
    "google_scholar_url": ("Google Scholar link", "رابط Google Scholar"), "publications": ("Publications", "المنشورات"),
    "is_partner": ("Partner (show logo)", "شريك (إظهار الشعار)"), "label": ("Label", "التسمية"), "value": ("Value", "القيمة"),
    "suffix": ("Suffix", "اللاحقة"), "crm_status": ("CRM sync", "المزامنة مع CRM"),
    "ga_measurement_id": ("Google Analytics ID", "معرّف Google Analytics"), "plausible_domain": ("Plausible domain", "نطاق Plausible"),
    "privacy_url": ("Privacy policy link", "رابط سياسة الخصوصية"),
    "content_type": ("Content type", "نوع المحتوى"), "open_access": ("Open access", "وصول مفتوح"), "published_date": ("Published date", "تاريخ النشر"),
    "received_date": ("Received date", "تاريخ الاستلام"), "accepted_date": ("Accepted date", "تاريخ القبول"), "volume": ("Volume", "المجلد"),
    "issue": ("Issue", "العدد"), "article_number": ("Article number", "رقم المقال"), "publisher": ("Publisher", "الناشر"), "issn": ("ISSN", "ISSN"),
    "license": ("License", "الترخيص"), "license_url": ("License link", "رابط الترخيص"), "keywords": ("Keywords", "الكلمات المفتاحية"),
    "subjects": ("Subjects", "المواضيع"), "abstract": ("Abstract", "الملخص"), "abstract_background": ("Abstract: Background", "الملخص: الخلفية"),
    "abstract_methods": ("Abstract: Methods", "الملخص: المنهجية"), "abstract_results": ("Abstract: Results", "الملخص: النتائج"),
    "abstract_conclusion": ("Abstract: Conclusion", "الملخص: الخلاصة"), "rights_text": ("Rights and permissions text", "نص الحقوق والأذونات"),
    "accesses": ("Accesses", "مرات الوصول"), "citations": ("Citations", "الاستشهادات"), "altmetric": ("Altmetric", "Altmetric"), "mentions": ("Mentions", "الإشارات"),
    "given_name": ("Given name", "الاسم الأول"), "family_name": ("Family name", "اسم العائلة"), "corresponding": ("Corresponding author", "المؤلف المراسل"),
    "number": ("Number", "الرقم"), "caption": ("Caption", "التعليق"), "table_html": ("Table HTML", "جدول بصيغة HTML"), "note": ("Note", "ملاحظة"),
    "text": ("Reference text", "نص المرجع"), "source": ("Source", "المصدر"), "url": ("URL", "الرابط"), "heading": ("Heading", "العنوان الفرعي"),
    "announcement_text": ("Announcement text", "نص الإعلان"), "announcement_url": ("Announcement link", "رابط الإعلان"), "publication": ("Publication", "المنشور"),
    "website": ("Website", "الموقع الإلكتروني"), "year": ("Year", "السنة"),
}

HELP = {
    "Short 'about SiaNexis' text on the home page.": "نص تعريفي قصير عن SiaNexis يظهر في الصفحة الرئيسية.",
    "Optional tracking script (e.g. analytics).": "كود تتبع اختياري (مثل التحليلات).",
    "Leave blank to use the title.": "اتركه فارغًا لاستخدام العنوان.",
    "Untick to hide from the public site.": "ألغِ التحديد لإخفائه عن الموقع.",
    "Lower numbers appear first.": "الأرقام الأصغر تظهر أولًا.",
    "Auto-filled from the title.": "يُملأ تلقائيًا من العنوان.",
    "Plain text. Blank lines become paragraphs.": "نص عادي. الأسطر الفارغة تصبح فقرات.",
    "An emoji or short symbol.": "رمز تعبيري أو رمز قصير.",
    "Show on the home page.": "إظهاره في الصفحة الرئيسية.",
    "e.g. 10.1000/xyz123 (no URL prefix)": "مثال: 10.1000/xyz123 (بدون بادئة الرابط)",
    "Online / In person / Hybrid": "عن بُعد / حضوري / مختلط",
    "External link. Leave blank to use the built-in registration form.": "رابط خارجي. اتركه فارغًا لاستخدام نموذج التسجيل المدمج.",
    "Maximum seats. Leave blank for unlimited; extra sign-ups go on a waiting list.": "الحد الأقصى للمقاعد. اتركه فارغًا لعدد غير محدود؛ والتسجيلات الزائدة تُضاف إلى قائمة الانتظار.",
    "Optional: show on the site from this date/time.": "اختياري: العرض في الموقع اعتبارًا من هذا التاريخ والوقت.",
    "Optional: hide from the site after this date/time.": "اختياري: الإخفاء من الموقع بعد هذا التاريخ والوقت.",
    "Position on the map. Use the 'Fill coordinates from country' action, or enter manually.": "الموقع على الخريطة. استخدم إجراء «ملء الإحداثيات من الدولة» أو أدخله يدويًا.",
    "e.g. 0000-0002-1825-0097": "مثال: 0000-0002-1825-0097",
    "Show this logo in the partners strip on the home page.": "إظهار هذا الشعار في شريط الشركاء بالصفحة الرئيسية.",
    "e.g. + or %": "مثال: + أو %",
    "Google Analytics 4 ID, e.g. G-XXXXXXXXXX. Loaded only after the visitor accepts cookies.": "معرّف Google Analytics 4 مثل G-XXXXXXXXXX. لا يُحمَّل إلا بعد موافقة الزائر على ملفات الكوكيز.",
    "Plausible domain, e.g. sianexis.com (cookie-free analytics).": "نطاق Plausible مثل sianexis.com (تحليلات بدون كوكيز).",
    "Link of the privacy policy page, e.g. /en/p/privacy/": "رابط صفحة سياسة الخصوصية، مثل /ar/p/privacy/",
    "Use this for an unstructured abstract.": "استخدمه لملخص غير مقسّم إلى أجزاء.",
    "Comma separated.": "افصل بفاصلة.", "Comma separated. Shown as related subjects.": "افصل بفاصلة. تظهر كمواضيع ذات صلة.",
    "e.g. CC BY 4.0": "مثال: CC BY 4.0", "Rights and permissions statement.": "بيان الحقوق والأذونات.",
    "Full name as displayed.": "الاسم الكامل كما يظهر.", "Optional, for correct citations.": "اختياري، لضبط صيغة الاستشهاد.",
    "Leave blank to use the standard title.": "اتركه فارغًا لاستخدام العنوان القياسي.",
    "Blank line = new paragraph. '### Title' = sub-heading. '- item' = bullet. [12] links to reference 12. [[fig:1]] / [[table:1]] place a figure or table.": "سطر فارغ = فقرة جديدة. '### عنوان' = عنوان فرعي. '- عنصر' = نقطة. [12] يربط بالمرجع 12. [[fig:1]] / [[table:1]] لوضع شكل أو جدول.",
    "e.g. Fig. 1 or Table 1": "مثال: Fig. 1 أو Table 1", "HTML <table> for tables.": "جدول HTML للجداول.", "Footnote under the figure/table.": "حاشية أسفل الشكل/الجدول.",
    "Full reference as printed.": "المرجع كاملًا كما هو مطبوع.", "Journal / publisher and year.": "المجلة / الناشر والسنة.",
    "Optional notice bar shown at the top of article pages.": "شريط تنبيه اختياري يظهر أعلى صفحات الأبحاث.",
    "Leave blank to use the contact form.": "اتركه فارغًا لاستخدام نموذج التواصل.",
    "Shown on the post and used for ordering.": "يظهر على المقال ويُستخدم في الترتيب.",
}

# model class name -> (singular, plural, singular_ar, plural_ar)
MODELS = {
    "SiteSettings": ("Site settings", "Site settings", "إعدادات الموقع", "إعدادات الموقع"),
    "Page": ("Page", "Pages", "صفحة", "الصفحات"),
    "AboutSection": ("About section", "About sections", "قسم من نحن", "أقسام من نحن"),
    "TeamMember": ("Team member", "Team members", "عضو فريق", "أعضاء الفريق"),
    "ResearchArea": ("Research area", "Research areas", "مجال بحثي", "المجالات البحثية"),
    "ServiceCategory": ("Service category", "Service categories", "تصنيف خدمات", "تصنيفات الخدمات"),
    "Service": ("Service", "Services", "خدمة", "الخدمات"),
    "Organization": ("Organization", "Organizations", "مؤسسة", "المؤسسات"),
    "Collaboration": ("Collaboration", "Collaborations", "تعاون", "التعاونات"),
    "Project": ("Project", "Projects", "مشروع", "المشروعات"),
    "Publication": ("Publication", "Publications", "منشور", "المنشورات"),
    "HubItem": ("Research Hub item", "Research Hub items", "عنصر في مركز الأبحاث", "عناصر مركز الأبحاث"),
    "TrainingProgram": ("Training program", "Training programs", "برنامج تدريبي", "البرامج التدريبية"),
    "Opportunity": ("Opportunity", "Opportunities", "فرصة", "الفرص"),
    "Metric": ("Impact metric", "Impact metrics", "مؤشر أثر", "مؤشرات الأثر"),
    "ArticleAuthor": ("Article author", "Article authors", "مؤلف المقال", "مؤلفو المقال"),
    "ArticleSection": ("Article section", "Article sections", "قسم في المقال", "أقسام المقال"),
    "ArticleFigure": ("Figure / table", "Figures & tables", "شكل / جدول", "الأشكال والجداول"),
    "ArticleReference": ("Reference", "References", "مرجع", "المراجع"),
    "ArticleLink": ("Similar / related link", "Similar / related links", "رابط مشابه / ذو صلة", "روابط مشابهة / ذات صلة"),
    "ContactRequest": ("Contact request", "Contact requests", "طلب تواصل", "طلبات التواصل"),
    "Post": ("News post", "News posts", "خبر", "الأخبار"),
    "NewsletterSubscriber": ("Newsletter subscriber", "Newsletter subscribers", "مشترك في النشرة", "مشتركو النشرة البريدية"),
    "TrainingRegistration": ("Training registration", "Training registrations", "تسجيل في تدريب", "تسجيلات التدريب"),
}

ADMIN = {
    "SiaNexis CMS": "لوحة تحكم SiaNexis", "Manage website content": "إدارة محتوى الموقع", "Website content": "محتوى الموقع",
    "Website": "الموقع", "Research & publications": "الأبحاث والمنشورات", "Engagement": "التفاعل والطلبات", "Users & access": "المستخدمون والصلاحيات",
    "View website": "عرض الموقع", "New contact requests": "طلبات تواصل جديدة", "Pending training registrations": "تسجيلات تدريب قيد المراجعة",
    "Waiting-list registrations": "تسجيلات في قائمة الانتظار", "Active newsletter subscribers": "مشتركون نشطون في النشرة",
    "Needs attention": "يحتاج إلى متابعة", "Quick add": "إضافة سريعة", "Edit site settings": "تعديل إعدادات الموقع",
    "SEO": "تحسين محركات البحث (SEO)", "Details": "التفاصيل", "Publishing": "النشر", "Settings & contact": "الإعدادات والتواصل",
    "Assign selected to me": "إسناد المحدد إليّ", "Mark as in progress": "تحديد كـ قيد التنفيذ", "Mark as closed": "تحديد كـ مغلق",
    "Export selected requests as CSV": "تصدير الطلبات المحددة بصيغة CSV", "Export selected subscribers as CSV": "تصدير المشتركين المحددين بصيغة CSV",
    "Export selected registrations as CSV": "تصدير التسجيلات المحددة بصيغة CSV", "Confirm selected registrations": "تأكيد التسجيلات المحددة",
    "Fill missing details from DOI (Crossref)": "ملء البيانات الناقصة من DOI (Crossref)", "Seats (taken / capacity)": "المقاعد (المحجوزة / السعة)",
    "Visibility": "الظهور", "Live": "منشور", "Scheduled": "مجدول", "Expired": "منتهٍ", "Draft": "مسودة", "On map": "على الخريطة",
    "Publish selected (make live now)": "نشر المحدد الآن", "Unpublish selected (draft)": "إلغاء نشر المحدد (مسودة)",
    "%(n)s item(s) published.": "تم نشر %(n)s عنصر/عناصر.", "%(n)s item(s) moved to draft.": "تم نقل %(n)s عنصر/عناصر إلى المسودات.",
    "Fill coordinates from country": "ملء الإحداثيات من الدولة", "%(n)s collaboration(s) placed on the map.": "تمت إضافة %(n)s تعاون/تعاونات إلى الخريطة.",
    "Send selected to CRM again": "إرسال المحدد إلى CRM مرة أخرى", "No CRM is configured (set CRM_WEBHOOK_URL or HUBSPOT_TOKEN).": "لم يتم إعداد CRM (اضبط CRM_WEBHOOK_URL أو HUBSPOT_TOKEN).",
    "%(n)s request(s) queued for the CRM.": "تمت جدولة %(n)s طلب/طلبات للإرسال إلى CRM.",
    "Language": "اللغة", "English": "English", "Project description": "وصف المشروع",
}
