// Generates firestore.rules from the content schema so every content collection gets identical rules.
// Run:  node tools/gen_rules.mjs
import fs from 'node:fs';
import { SCHEMA } from '../src/schema.js';

const D = '/databases/$(database)/documents';
const publishable = Object.entries(SCHEMA).filter(([, s]) => s.publish).map(([k]) => k);
const plain = Object.entries(SCHEMA).filter(([, s]) => !s.publish).map(([k]) => k);

const contentRules = [
  ...publishable.map((c) => `    match /${c}/{id} {
      allow get: if live(resource.data) || staff();
      allow list: if staff();
      allow create, update: if staff();
      allow delete: if editor();
    }`),
  ...plain.map((c) => `    match /${c}/{id} {
      allow get, list: if staff();
      allow create, update: if staff();
      allow delete: if editor();
    }`),
].join('\n');

const rules = `rules_version = '2';
// GENERATED by tools/gen_rules.mjs - edit the generator, not this file.
service cloud.firestore {
  match /databases/{database}/documents {

    // ---------------------------------------------------------------- helpers
    function signedIn() { return request.auth != null; }
    function verified() { return signedIn() && request.auth.token.email_verified == true; }
    function isAdminDoc() { return signedIn() && exists(${D}/admins/$(request.auth.uid)); }
    function role() { return get(${D}/admins/$(request.auth.uid)).data.role; }
    function staff() { return isAdminDoc(); }
    function editor() { return isAdminDoc() && role() in ['admin', 'editor']; }
    function siteAdmin() { return isAdminDoc() && role() == 'admin'; }
    function live(d) {
      return d.is_published == true
        && (!('publish_at' in d) || d.publish_at == null || d.publish_at <= request.time)
        && (!('unpublish_at' in d) || d.unpublish_at == null || d.unpublish_at > request.time);
    }
    function str(v, max) { return v is string && v.size() <= max; }
    function okEmail(v) { return v is string && v.size() <= 254 && v.matches('^[^@\\\\s]+@[^@\\\\s]+\\\\.[^@\\\\s]+$'); }
    function enrolled(program) {
      return verified()
        && exists(${D}/enrollments/$(request.auth.uid + '__' + program))
        && get(${D}/enrollments/$(request.auth.uid + '__' + program)).data.status in ['approved', 'completed'];
    }

    // ------------------------------------------------------- staff & roles
    match /admins/{uid} {
      allow get: if signedIn() && (request.auth.uid == uid || staff());
      allow list: if siteAdmin();
      allow create, update, delete: if siteAdmin();
    }

    // ----------------------------------------------------- public content
${contentRules}

    match /settings/{id} {
      allow get, list: if staff();
      allow write: if editor();
    }

    // Pre-built public copies of the content (one read per collection for visitors).
    match /snapshots/{id} {
      allow read: if true;
      allow write: if staff();
    }

    match /history/{id} {
      allow read, create: if staff();
      allow delete: if editor();
      allow update: if false;
    }

    // ------------------------------------------------------ public forms
    match /contactRequests/{id} {
      allow create: if request.resource.data.keys().hasOnly(['request_type', 'name', 'email', 'organization', 'subject', 'message', 'status', 'internal_notes', 'language', 'created'])
        && request.resource.data.request_type in ['research_project', 'data_analysis', 'collaboration', 'multicenter', 'partnership', 'training', 'other']
        && str(request.resource.data.name, 120) && request.resource.data.name.size() > 0
        && okEmail(request.resource.data.email)
        && str(request.resource.data.organization, 200) && str(request.resource.data.subject, 200)
        && str(request.resource.data.message, 5000) && request.resource.data.message.size() > 0
        && request.resource.data.status == 'new' && request.resource.data.internal_notes == ''
        && str(request.resource.data.language, 5) && request.resource.data.created == request.time;
      allow get, list, update: if staff();
      allow delete: if editor();
    }

    match /subscriberEmails/{key} {
      allow create: if request.resource.data.keys().hasOnly(['token', 'created'])
        && str(request.resource.data.token, 64) && request.resource.data.token.size() >= 16 && request.resource.data.created == request.time;
      allow get, list: if staff();
      allow delete: if editor();
    }

    match /subscribers/{token} {
      allow get: if true;   // the unguessable token in the unsubscribe link is the credential
      allow list: if staff();
      allow create: if request.resource.data.keys().hasOnly(['email', 'language', 'is_active', 'created', 'emailKey'])
        && okEmail(request.resource.data.email) && request.resource.data.is_active == true
        && str(request.resource.data.language, 5) && request.resource.data.created == request.time
        && existsAfter(${D}/subscriberEmails/$(request.resource.data.emailKey))
        && getAfter(${D}/subscriberEmails/$(request.resource.data.emailKey)).data.token == token;
      allow update: if staff()
        || (request.resource.data.diff(resource.data).affectedKeys().hasOnly(['is_active']) && request.resource.data.is_active == false);
      allow delete: if editor();
    }

    // Seat counters: only change together with a registration (or by editors).
    match /trainingStats/{slug} {
      allow read: if true;
      allow create: if request.resource.data.keys().hasOnly(['taken', 'last']) && request.resource.data.taken == 1
        && !exists(${D}/registrations/$(request.resource.data.last))
        && existsAfter(${D}/registrations/$(request.resource.data.last))
        && getAfter(${D}/registrations/$(request.resource.data.last)).data.program == slug
        && getAfter(${D}/registrations/$(request.resource.data.last)).data.status == 'pending'
        || editor();
      allow update: if editor()
        || (request.resource.data.keys().hasOnly(['taken', 'last']) && request.resource.data.taken == resource.data.taken + 1
          && !exists(${D}/registrations/$(request.resource.data.last))
          && existsAfter(${D}/registrations/$(request.resource.data.last))
          && getAfter(${D}/registrations/$(request.resource.data.last)).data.program == slug
          && getAfter(${D}/registrations/$(request.resource.data.last)).data.status == 'pending')
        || (request.resource.data.keys().hasOnly(['taken', 'last']) && request.resource.data.taken == resource.data.taken - 1
          && get(${D}/registrations/$(request.resource.data.last)).data.status in ['pending', 'confirmed']
          && getAfter(${D}/registrations/$(request.resource.data.last)).data.status == 'cancelled'
          && get(${D}/registrations/$(request.resource.data.last)).data.uid == request.auth.uid);
      allow delete: if editor();
    }

    match /registrations/{id} {
      allow create: if request.resource.data.keys().hasOnly(['program', 'program_title', 'name', 'email', 'organization', 'phone', 'message', 'status', 'language', 'uid', 'created'])
        && id == request.resource.data.program + '__' + id.split('__')[1]
        && str(request.resource.data.name, 120) && request.resource.data.name.size() > 0
        && okEmail(request.resource.data.email)
        && str(request.resource.data.organization, 200) && str(request.resource.data.phone, 40) && str(request.resource.data.message, 3000)
        && str(request.resource.data.program_title, 300) && str(request.resource.data.language, 5)
        && (request.resource.data.uid == '' || (verified() && request.resource.data.uid == request.auth.uid && request.resource.data.email == request.auth.token.email.lower()))
        && request.resource.data.created == request.time
        && live(get(${D}/training/$(request.resource.data.program)).data)
        && get(${D}/training/$(request.resource.data.program)).data.registration_open == true
        && get(${D}/training/$(request.resource.data.program)).data.get('registration_link', '') == ''
        && (
          (request.resource.data.status == 'pending'
            && (get(${D}/training/$(request.resource.data.program)).data.get('capacity', null) == null
                || (exists(${D}/trainingStats/$(request.resource.data.program)) ? get(${D}/trainingStats/$(request.resource.data.program)).data.taken : 0)
                   < get(${D}/training/$(request.resource.data.program)).data.capacity)
            && getAfter(${D}/trainingStats/$(request.resource.data.program)).data.last == id
            && getAfter(${D}/trainingStats/$(request.resource.data.program)).data.taken
               == (exists(${D}/trainingStats/$(request.resource.data.program)) ? get(${D}/trainingStats/$(request.resource.data.program)).data.taken : 0) + 1)
          ||
          (request.resource.data.status == 'waitlist'
            && get(${D}/training/$(request.resource.data.program)).data.get('capacity', null) != null
            && (exists(${D}/trainingStats/$(request.resource.data.program)) ? get(${D}/trainingStats/$(request.resource.data.program)).data.taken : 0)
               >= get(${D}/training/$(request.resource.data.program)).data.capacity)
        );
      allow get: if staff() || (verified() && resource.data.email == request.auth.token.email.lower());
      allow list: if staff();
      allow update: if staff()
        || (signedIn() && resource.data.uid == request.auth.uid && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['status'])
            && request.resource.data.status == 'cancelled');
      allow delete: if editor();
    }

    // ------------------------------------------------------ student portal
    match /students/{uid} {
      allow get: if (verified() && request.auth.uid == uid) || staff();
      allow list: if staff();
      allow create: if verified() && request.auth.uid == uid
        && request.resource.data.keys().hasOnly(['full_name', 'email', 'university', 'field_of_study', 'phone', 'language', 'created'])
        && request.resource.data.email == request.auth.token.email.lower()
        && str(request.resource.data.full_name, 120) && str(request.resource.data.university, 200) && str(request.resource.data.field_of_study, 160)
        && str(request.resource.data.phone, 40) && str(request.resource.data.language, 5);
      allow update: if (verified() && request.auth.uid == uid
        && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['full_name', 'university', 'field_of_study', 'phone', 'language'])
        && str(request.resource.data.full_name, 120) && str(request.resource.data.university, 200) && str(request.resource.data.field_of_study, 160)
        && str(request.resource.data.phone, 40) && str(request.resource.data.language, 5)) || editor();
      allow delete: if editor();
    }

    match /enrollments/{id} {
      allow get: if (verified() && resource.data.uid == request.auth.uid) || staff();
      allow list: if staff() || (verified() && resource.data.uid == request.auth.uid);
      allow create: if verified() && request.resource.data.keys().hasOnly(['uid', 'program', 'program_title', 'status', 'note', 'registration', 'created', 'updated'])
        && request.resource.data.uid == request.auth.uid && id == request.auth.uid + '__' + request.resource.data.program
        && request.resource.data.status in ['pending', 'waitlist'] && request.resource.data.note == ''
        && str(request.resource.data.program_title, 300)
        && request.resource.data.created == request.time && request.resource.data.updated == request.time
        && (exists(${D}/registrations/$(request.resource.data.registration)) || existsAfter(${D}/registrations/$(request.resource.data.registration)))
        && getAfter(${D}/registrations/$(request.resource.data.registration)).data.email == request.auth.token.email.lower()
        && getAfter(${D}/registrations/$(request.resource.data.registration)).data.status == request.resource.data.status
        && getAfter(${D}/registrations/$(request.resource.data.registration)).data.program == request.resource.data.program;
      allow update: if staff()
        || (verified() && resource.data.uid == request.auth.uid && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['status', 'updated'])
            && request.resource.data.status == 'cancelled' && resource.data.status in ['pending', 'waitlist', 'approved']);
      allow delete: if editor();
    }

    match /projectRequests/{id} {
      allow get: if (verified() && resource.data.uid == request.auth.uid) || staff();
      allow list: if staff() || (verified() && resource.data.uid == request.auth.uid);
      allow create: if verified() && request.resource.data.keys().hasOnly(['uid', 'title', 'summary', 'research_area', 'supervisor', 'attachment', 'attachment_name', 'status', 'review_note', 'submitted_at', 'project', 'created', 'updated'])
        && request.resource.data.uid == request.auth.uid && request.resource.data.status in ['draft', 'submitted']
        && str(request.resource.data.title, 200) && request.resource.data.title.size() > 0 && str(request.resource.data.summary, 8000) && request.resource.data.summary.size() > 0
        && str(request.resource.data.supervisor, 160) && request.resource.data.review_note == '' && request.resource.data.project == ''
        && request.resource.data.created == request.time && request.resource.data.updated == request.time;
      allow update: if staff()
        || (verified() && resource.data.uid == request.auth.uid && resource.data.status in ['draft', 'rejected']
            && request.resource.data.status in ['draft', 'submitted']
            && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['title', 'summary', 'research_area', 'supervisor', 'attachment', 'attachment_name', 'status', 'submitted_at', 'updated'])
            && str(request.resource.data.title, 200) && request.resource.data.title.size() > 0 && str(request.resource.data.summary, 8000) && request.resource.data.summary.size() > 0);
      allow delete: if editor() || (verified() && resource.data.uid == request.auth.uid && resource.data.status == 'draft');
    }

    match /materials/{id} {
      allow get, list: if staff() || enrolled(resource.data.program);
      allow create, update: if editor();
      allow delete: if editor();
    }

    // Private files (student attachments, course materials) stored in Firestore as base64 chunks.
    match /files/{fid} {
      allow get: if staff() || (verified() && resource.data.owner == request.auth.uid) || (resource.data.kind == 'material' && enrolled(resource.data.program));
      allow list: if staff();
      allow create: if (editor() && request.resource.data.kind == 'material')
        || (verified() && request.resource.data.owner == request.auth.uid && request.resource.data.kind == 'attachment'
            && request.resource.data.size <= 5242880 && request.resource.data.chunks <= 8);
      allow delete: if editor() || (verified() && resource.data.owner == request.auth.uid);
      allow update: if false;
      match /chunks/{i} {
        allow get: if staff() || (verified() && get(${D}/files/$(fid)).data.owner == request.auth.uid)
          || (get(${D}/files/$(fid)).data.kind == 'material' && enrolled(get(${D}/files/$(fid)).data.program));
        allow create: if (editor()) || (verified() && get(${D}/files/$(fid)).data.owner == request.auth.uid && str(request.resource.data.data, 720000));
        allow delete: if editor() || (verified() && get(${D}/files/$(fid)).data.owner == request.auth.uid);
        allow update: if false;
      }
    }

    match /notifications/{id} {
      allow get: if signedIn() && resource.data.uid == request.auth.uid;
      allow list: if staff() || (signedIn() && resource.data.uid == request.auth.uid);
      allow create: if staff()
        || (verified() && request.resource.data.uid == request.auth.uid && request.resource.data.keys().hasOnly(['uid', 'text', 'url', 'read', 'created'])
            && str(request.resource.data.text, 300) && str(request.resource.data.url, 200) && request.resource.data.read == false && request.resource.data.created == request.time);
      allow update: if signedIn() && resource.data.uid == request.auth.uid && request.resource.data.diff(resource.data).affectedKeys().hasOnly(['read']);
      allow delete: if editor() || (signedIn() && resource.data.uid == request.auth.uid);
    }

    match /{other=**} { allow read, write: if false; }
  }
}
`;
fs.writeFileSync(new URL('../firestore.rules', import.meta.url), rules);
console.log('firestore.rules written (' + rules.split('\n').length + ' lines)');
